In [3]:
import numpy as np

In [7]:
x = np.array([2,3,6,77,55,44,77,99,78,34])
t = np.where((x>=20) & (x<=99))
x[t]

array([77, 55, 44, 77, 99, 78, 34])

In [8]:
len(x[t])

7

In [9]:
((x>=20) & (x<=99)).sum()

7

In [10]:
np.in1d(x,[2,3,6])

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [13]:
np.where(np.in1d(x,[2,3,6]))

(array([0, 1, 2], dtype=int64),)

## Sets

In [16]:
x1 = np.array([4,6,7,8,9])
x2 = np.array([3,8,9])

In [23]:
np.intersect1d(x1,x2) #elements common in both x1 and x2

array([8, 9])

In [18]:
np.union1d(x1,x2)

array([3, 4, 6, 7, 8, 9])

In [21]:
np.setdiff1d(x1,x2) #elements present in x1 but not in x2

array([4, 6, 7])

In [22]:
np.setxor1d(x1,x2) #all elements not common in x1 and x2

array([3, 4, 6, 7])

## random numbers between 10 and 20 

In [25]:
from numpy import random
r = np.random.randint(10,20,10)
r

array([13, 14, 11, 11, 19, 16, 14, 10, 12, 14])

In [27]:
z = np.round(np.random.rand(10),2)
z

array([0.52, 0.12, 0.57, 0.7 , 0.62, 0.58, 0.4 , 0.58, 0.91, 0.11])

In [31]:
r1 = r+z
r1

array([13.52, 14.12, 11.57, 11.7 , 19.62, 16.58, 14.4 , 10.58, 12.91,
       14.11])

# pandas

In [33]:
import pandas as pd
x = pd.Series([10,20,30])
type(x)

pandas.core.series.Series