In [1]:
import numpy as np

In [2]:
w1 = np.array([4,5,7,8])
w2 = np.array([9,4,2,1])

In [29]:
ar1 = np.array([w1,w2])
ar1

array([[4, 5, 7, 8],
       [9, 4, 2, 1]])

In [21]:
print(np.shape(ar1))


(2, 4)


In [30]:
ar2 = np.array([2,2,2,2])

In [31]:
ar1 = np.vstack([ar2,ar1])
ar1

array([[2, 2, 2, 2],
       [4, 5, 7, 8],
       [9, 4, 2, 1]])

In [32]:
ar_left = ar1[:,:3]
ar_left

array([[2, 2, 2],
       [4, 5, 7],
       [9, 4, 2]])

In [33]:
ar_right = ar1[:,3:]
ar_right

array([[2],
       [8],
       [1]])

In [35]:
x = np.array([9,9,9])
x = x.reshape(3,1)
x

array([[9],
       [9],
       [9]])

In [37]:
new_ar = np.hstack([ar_left,x,ar_right])
new_ar

array([[2, 2, 2, 9, 2],
       [4, 5, 7, 9, 8],
       [9, 4, 2, 9, 1]])

In [38]:
new_ar[1]

array([4, 5, 7, 9, 8])

In [40]:
n = np.sort(new_ar,axis=1)
n

array([[2, 2, 2, 2, 9],
       [4, 5, 7, 8, 9],
       [1, 2, 4, 9, 9]])

In [55]:
n = np.sort(new_ar,axis=0)
n

array([[2, 2, 2, 9, 1],
       [4, 4, 2, 9, 2],
       [9, 5, 7, 9, 8]])

In [45]:
n[:,[1,2,3]]

array([[2, 2, 9],
       [4, 2, 9],
       [5, 7, 9]])

In [50]:
n[[1,2],:2]

array([[4, 4],
       [9, 5]])

In [58]:
n = np.delete(n,3,axis=1)
n

array([[2, 2, 2],
       [4, 4, 2],
       [9, 5, 7]])

## When you delete 0th index from a 2d array it deletes its one dimension


In [52]:
n = np.delete(n,0)

In [53]:
n

array([2, 2, 1, 4, 4, 2, 2, 9, 5, 7, 8])

## Now deleting using axis = 0

In [59]:
n = np.delete(n,0,axis=0)

In [60]:
n

array([[4, 4, 2],
       [9, 5, 7]])

In [61]:
n = np.insert(n,0,[4,7,8],axis=0)
n

array([[4, 7, 8],
       [4, 4, 2],
       [9, 5, 7]])

In [62]:
n = np.insert(n,3,[1,2,3],axis=1)
n

array([[4, 7, 8, 1],
       [4, 4, 2, 2],
       [9, 5, 7, 3]])

# Filtering 

In [67]:
x = np.where(n>2)
x

(array([0, 0, 0, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2, 3], dtype=int64))

In [68]:
n[x]

array([4, 7, 8, 4, 4, 9, 5, 7, 3])