In [1]:
import numpy as np
import pandas as pd
from numpy import random

## using 2 conditions to filter


In [30]:
x1 = np.array([3,8,7,6,5,10,5,0,10])
w1 = np.where((x1>=4) & (x1<=8))
x1[w1]

array([8, 7, 6, 5, 5])

In [32]:
t1 = np.where((x1>=4) & (x1<=8))
x1[t1]

array([8, 7, 6, 5, 5])

In [33]:
t1[0]

array([1, 2, 3, 4, 6], dtype=int64)

In [35]:
x1[t1[0]] #same as x1[t1]

array([8, 7, 6, 5, 5])

In [38]:
((x1>=4) & (x1<=8)).sum() #easier way to figure out count

5

In [39]:
((x1>=4) & (x1<=8))

array([False,  True,  True,  True,  True, False,  True, False, False])

## Broadcasting across an array.

In [42]:
x2 = np.array([6,4,7,8,9,0])
x3 = x2+3
x3

array([ 9,  7, 10, 11, 12,  3])

In [57]:
x2 = np.array([3,4,5,1,2,8,9,32,56,78,11,12])
x2 = x2.reshape(3,4)
x2

array([[ 3,  4,  5,  1],
       [ 2,  8,  9, 32],
       [56, 78, 11, 12]])

In [47]:
x3 = np.array([1,3,5,7])
x3

array([1, 3, 5, 7])

In [48]:
x2 + x3


array([[ 4,  7, 10,  8],
       [ 3, 11, 14, 39],
       [57, 81, 16, 19]])

In [49]:
x2*3

array([[  9,  12,  15,   3],
       [  6,  24,  27,  96],
       [168, 234,  33,  36]])

In [59]:
x4 = np.array([3,5,7])
x4=x4.reshape(3,1)

In [60]:
x2+x4

array([[ 6,  7,  8,  4],
       [ 7, 13, 14, 37],
       [63, 85, 18, 19]])

In [64]:
x1=np.array([4,9,6,2,3,4,5,7,6,5,4,8,9])
x2 = np.unique(x1)
x2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
4 in x2 #elemts present in a list

True

In [67]:
10 in x2

False

In [68]:
(4 in x1) | (6 in x1) | (10 in x1)

True

In [69]:
np.in1d(x1,[4,6,10])

array([ True, False,  True, False, False,  True, False, False,  True,
       False,  True, False, False])

In [70]:
np.where(np.in1d(x1,[4,6,10]))

(array([ 0,  2,  5,  8, 10], dtype=int64),)

## sets

In [71]:
x1 = np.array([2,9,4,7,1,5])

In [72]:
x2 = np.array([4,8,6,3,7])

In [74]:
np.intersect1d(x1,x2)

array([4, 7])

In [75]:
np.union1d(x1,x2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.setdiff1d(x1,x2)

array([1, 2, 5, 9])

In [77]:
np.setxor1d(x1,x2)

array([1, 2, 3, 5, 6, 8, 9])

## RANDOM


In [80]:
np.random.rand(10)

array([0.45440621, 0.54375675, 0.62060479, 0.83238701, 0.34589512,
       0.61468497, 0.10207845, 0.93004704, 0.48441986, 0.41921038])

In [39]:
np.round(np.random.rand(10),3)

array([0.742, 0.533, 0.996, 0.313, 0.469, 0.428, 0.4  , 0.917, 0.34 ,
       0.329])

In [84]:
np.random.randint(20,40)

28

## 10 random numbers between 20 and 30 rounding upto 2 decimal palces

In [98]:
x1 = np.random.randint(20,30,10)
x1

array([20, 22, 25, 28, 20, 24, 24, 21, 22, 27])

In [99]:
x2 = np.round(np.random.rand(10),2)
x2

array([0.24, 0.17, 0.45, 0.87, 0.16, 0.06, 0.59, 0.79, 0.82, 0.88])

In [102]:
xe = x1+x2
xe

array([20.24, 22.17, 25.45, 28.87, 20.16, 24.06, 24.59, 21.79, 22.82,
       27.88])

# Pandas


In [104]:
x1 = [3,6,5,7]

In [105]:
p1 = pd.Series(x1)

In [106]:
type(p1)

pandas.core.series.Series

In [107]:
p1

0    3
1    6
2    5
3    7
dtype: int64

In [108]:
p2 = pd.Series(x1,index=['A','B','C','D'])
p2

A    3
B    6
C    5
D    7
dtype: int64

In [109]:

p2[2]

C:\Users\dheem\AppData\Local\Temp\ipykernel_10640\2048921606.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p2[2]


5

In [110]:
p2['C']

5

In [142]:
x1 = {"Sachin":3423,"Virat":3698,"Dhoni":87485}

In [143]:
p2 = pd.Series(x1)
p2

Sachin     3423
Virat      3698
Dhoni     87485
dtype: int64

In [144]:
pn = pd.Series([5345,6475],index=['Rohit','Bumrah'])
pn

Rohit     5345
Bumrah    6475
dtype: int64

In [145]:
p2 = p2._append(pn)

In [146]:
p2

Sachin     3423
Virat      3698
Dhoni     87485
Rohit      5345
Bumrah     6475
dtype: int64

In [148]:
p2.drop(['Bumrah'])

Sachin     3423
Virat      3698
Dhoni     87485
Rohit      5345
dtype: int64

In [151]:
p2 = pd.concat([p2,pn])

In [152]:
p2

Sachin     3423
Virat      3698
Dhoni     87485
Rohit      5345
Bumrah     6475
Rohit      5345
Bumrah     6475
dtype: int64

# DataFrame

In [4]:
x1 = [['Amit',"MUM", 43],['Pankaj','BLR',35],['Swati','CHN',65]]
emp_df = pd.DataFrame(x1, columns = ["Name","Location","Salary"])

In [166]:
emp_df.iat[1,2]

35

In [172]:
emp_df.iat[1,2]=40

In [173]:
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      40
2   Swati      CHN      65

In [174]:
emp_df.at[0,'Location']

'MUM'

In [175]:
emp_df.at[0,'Location'] = 'DLI'

In [176]:
emp_df

Name Location  Salary
0    Amit      DLI      43
1  Pankaj      BLR      40
2   Swati      CHN      65

In [5]:
new_emp = pd.DataFrame([['Nalini','KOL',30],['Chetan','BLR',78]],columns = ['Name','Location','Salary'])
new_emp

Name Location  Salary
0  Nalini      KOL      30
1  Chetan      BLR      78

In [7]:
emp_df = emp_df._append(new_emp)

In [8]:
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      35
2   Swati      CHN      65
0  Nalini      KOL      30
1  Chetan      BLR      78

In [183]:
emp_df.loc[1]

Name Location  Salary
1  Pankaj      BLR      40
1  Chetan      BLR      78

In [184]:
emp_df.iloc[1]

Name        Pankaj
Location       BLR
Salary          40
Name: 1, dtype: object

In [9]:
emp_df.index = range(emp_df.shape[0])
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      35
2   Swati      CHN      65
3  Nalini      KOL      30
4  Chetan      BLR      78

In [190]:
x1 = [['Amit',"MUM", 43],['Pankaj','BLR',35],['Swati','CHN',65]]
emp_df = pd.DataFrame(x1, columns = ["Name","Location","Salary"])

In [191]:
new_emp = pd.DataFrame([['Nalini','KOL',30],['Chetan','BLR',78]],columns = ['Name','Location','Salary'])
new_emp

Name Location  Salary
0  Nalini      KOL      30
1  Chetan      BLR      78

In [188]:
emp_df = emp_df._append(new_emp, ignore_index=True) # using append
emp_df

In [195]:
emp_df = pd.concat([emp_df,new_emp]).reset_index(drop=True) #using concat
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      35
2   Swati      CHN      65
3  Nalini      KOL      30
4  Chetan      BLR      78
5  Nalini      KOL      30
6  Chetan      BLR      78

In [10]:
mydf = emp_df.iloc[[0,2,3]]
mydf

Name Location  Salary
0    Amit      MUM      43
2   Swati      CHN      65
3  Nalini      KOL      30

In [11]:
mydf.iloc[1]

Name        Swati
Location      CHN
Salary         65
Name: 2, dtype: object

In [12]:
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      35
2   Swati      CHN      65
3  Nalini      KOL      30
4  Chetan      BLR      78

In [13]:
newdf = emp_df.drop([1,3])
newdf

Name Location  Salary
0    Amit      MUM      43
2   Swati      CHN      65
4  Chetan      BLR      78

In [15]:
emp_df.Location

0    MUM
1    BLR
2    CHN
3    KOL
4    BLR
Name: Location, dtype: object

In [17]:
x1 = np.array(emp_df.Location)
x1

array(['MUM', 'BLR', 'CHN', 'KOL', 'BLR'], dtype=object)

In [19]:
x2 = list(emp_df.Location)
x2

['MUM', 'BLR', 'CHN', 'KOL', 'BLR']

In [20]:
emp_df

Name Location  Salary
0    Amit      MUM      43
1  Pankaj      BLR      35
2   Swati      CHN      65
3  Nalini      KOL      30
4  Chetan      BLR      78

In [22]:
tax = emp_df.Salary*0.10
tax

0    4.3
1    3.5
2    6.5
3    3.0
4    7.8
Name: Salary, dtype: float64

In [24]:
emp_df['Tax']=emp_df.Salary*0.10
emp_df

Name Location  Salary  tax  Tax
0    Amit      MUM      43  4.3  4.3
1  Pankaj      BLR      35  3.5  3.5
2   Swati      CHN      65  6.5  6.5
3  Nalini      KOL      30  3.0  3.0
4  Chetan      BLR      78  7.8  7.8

In [33]:
emp_df = emp_df.drop('tax', axis=1)

In [34]:
emp_df

Name Location  Salary  Tax
0    Amit      MUM      43  4.3
1  Pankaj      BLR      35  3.5
2   Swati      CHN      65  6.5
3  Nalini      KOL      30  3.0
4  Chetan      BLR      78  7.8

In [35]:
sal = emp_df[['Name','Salary']]
sal

Name  Salary
0    Amit      43
1  Pankaj      35
2   Swati      65
3  Nalini      30
4  Chetan      78

In [36]:
stu_names = ['Amit','Charanjeet','Vibha','Ruchika']
stu_marks = [68,54,98,50]

In [38]:
students = {'Name':stu_names,'Marks':stu_marks}
stu_df=pd.DataFrame(students)
stu_df

Name  Marks
0        Amit     68
1  Charanjeet     54
2       Vibha     98
3     Ruchika     50

In [39]:
import os 

In [40]:
os.getcwd()

'C:\\Users\\dheem\\Python\\Statistics and R'

In [41]:
#os.chdir(r'pathtofile') change directory to a file 

In [49]:
pip install openpyxl

   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.0 kB 653.6 kB/s eta 0:00:01
   ---------------------------------------- 250.0/250.0 kB 2.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name="ERPData")

In [3]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [5]:
df.shape

(50, 3)

In [8]:
warehouses = df['MaterialID'].unique()

In [12]:
np.unique(df.Location)

array(['MWH-1', 'MWH-2', 'MWH-3', 'MWH-4', 'MWH-5'], dtype=object)

In [11]:
len(np.unique(df.Location)) #count using np unique

5

### newdf.columns = df.columns ## transferring name of columns from one DF to another DF

### Criteria for a method to be betther  1. minimum number of steps 2. scalable

In [16]:
df[df.Quantity>=100]

MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
17    SDRT-67    MWH-5       102
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

In [17]:
len(df[df.Quantity>=100])

6

## using NumPy


In [22]:
qty = np.array([df.Quantity])
qty

array([[ 34,  67,  27,  65,  36,  78,  31,  29,  10, 120,  34,  58,  76,
         32,  65,  87,  12, 102,  34,  52,  39,  75,  48,  71, 152, 109,
         57,  83,  34,  57,  27,  65,  43, 112,  26,  31,  28,  65,  70,
        145,  34,  57,  31,  38,  42,  69,  85,  29,  75,  39]],
      dtype=int64)

In [25]:
cnt = qty[np.where(qty>=100)]
len(cnt)

6

In [34]:
len(np.where(df.Quantity>=100)[0])

6

## Sirs solution


In [36]:
t1 = np.where(df.Quantity>100)[0]
mydf = df.iloc[t1]
mydf

MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
17    SDRT-67    MWH-5       102
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
39    AXCP-78    MWH-1       145

# smartest way

In [37]:
(df.Quantity>=100).sum()

6