In [2]:
import numpy as np

In [2]:
r = np.arange(2,8)

In [15]:
r

array([2, 3, 4, 5, 6, 7])

In [4]:
r[3:5]

array([5, 6])

In [5]:
r[-5:-2]

array([3, 4, 5])

In [8]:
r1 = np.arange(9)

In [9]:
r1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
r1[-4:-1]

array([5, 6, 7])

In [3]:
r3 = np.arange(20,7,-4)
r3

array([20, 16, 12,  8])

## using insert, we pass the list to insert then the index, then the element to insert or list

In [4]:
r3=np.array([11,  4, 55, 66, 77,  7,  8,  9])
r3

array([11,  4, 55, 66, 77,  7,  8,  9])

## extracting multiple elements from indices

In [5]:
r3[[3,4,5]]

array([66, 77,  7])

In [6]:
r3 = np.array([11,4,8])

In [7]:
r4 = np.array([55,66,77])

In [8]:
r3 = np.insert(r3,2,r4)

In [9]:
r3

array([11,  4, 55, 66, 77,  8])

In [10]:
r3 = np.insert(r3,-1,7)

In [29]:
r3

array([11,  4, 55, 66, 77,  7,  8])

In [11]:
r3 = np.insert(r3,len(r3),9)

In [12]:
r3

array([11,  4, 55, 66, 77,  7,  8,  9])

## using concatenate


In [17]:
s1 = np.array([3,4,5])
s2 = np.array([11,22,66])
s1 = np.concatenate((s1,s2))
s1

array([ 3,  4,  5, 11, 22, 66])

## Using delete and passing the array followed by the index at which you want to delete

In [18]:
s1 = np.delete(s1,len(s1)-1)
s1
print(type(s1))

<class 'numpy.ndarray'>


In [15]:
w1 = [4,7,6,8]
w2 = [3,8,7,1]
ar1 = np.array([w1,w2])
ar1

array([[4, 7, 6, 8],
       [3, 8, 7, 1]])

In [13]:
print(type(ar1))

<class 'numpy.ndarray'>


In [23]:
ar1[0]

array([4, 7, 6, 8])

In [21]:
ar1[1]

array([3, 8, 7, 1])

In [24]:
ar1[1][3]

1

In [27]:
ar1[:,2:4]

array([[6, 8],
       [7, 1]])

In [32]:
ar2 = np.array(ar1[:,1:2])

In [33]:
ar2

array([[7],
       [8]])

In [34]:
ar3 = np.array(ar1[:,1:3])

In [35]:
ar3

array([[7, 6],
       [8, 7]])

In [37]:
x1 = np.array([1,3,2,5,6,73,5,4,87,99,3,8])
len(x1)

12

In [38]:
x2 = x1.reshape(3,4)
x2

array([[ 1,  3,  2,  5],
       [ 6, 73,  5,  4],
       [87, 99,  3,  8]])

In [19]:
ar2 = np.array([5,2,4,8])

In [20]:
ar1 = np.vstack([ar1,ar2])


In [21]:
ar1

array([[4, 7, 6, 8],
       [3, 8, 7, 1],
       [5, 2, 4, 8]])

## Inserting an array at column index 3

In [42]:
ar1

array([[4, 7, 6, 8],
       [3, 8, 7, 1],
       [5, 2, 4, 8]])

In [79]:
ar3 = np.array([5,4,9])
ar3 = ar3.reshape(3,1)
ar3

array([[5],
       [4],
       [9]])

In [46]:
ar1 = np.hstack([ar1,ar3])

In [82]:
ar1

array([[4, 7, 6, 4, 4, 7],
       [3, 8, 7, 3, 3, 8],
       [5, 2, 4, 9, 9, 2]])

In [80]:
ar1[1]

array([3, 8, 7, 3, 3, 8])

## extracting rows at index 2 and 1

In [81]:
ar1[[2,1]]

array([[5, 2, 4, 9, 9, 2],
       [3, 8, 7, 3, 3, 8]])

## for extracting rows and columns  
### we use ar1[:,[1,2,3]] for extracting columns at indices 1,2,3 
### we use ar1[:,3:] to extract all columns from index 3 to the end

## left eextractions

In [86]:
arleft = ar1[:,:3] #we are extracting columns at index 3 and 1 since they are 2 columnns they get stacked vertically
arleft

array([[4, 7, 6],
       [3, 8, 7],
       [5, 2, 4]])

In [87]:
## right extraactions

In [89]:
ar_right = ar1[:,3:]
ar_right

array([[4, 4, 7],
       [3, 3, 8],
       [9, 9, 2]])

## creating a new array then reshaping it 

In [61]:
ar4 = np.array([4,3,9])

In [72]:
ar4=ar4.reshape(3,1)


In [70]:
ar1=ar1[0:3,0:3]
ar1

array([[4, 7, 6],
       [3, 8, 7],
       [5, 2, 4]])

## we can use hstack all 3 arrays together

In [ ]:
ar1 = np.hstack([ar_left,newcol,ar_right])

In [90]:
ar1

array([[4, 7, 6, 4, 4, 7],
       [3, 8, 7, 3, 3, 8],
       [5, 2, 4, 9, 9, 2]])

# Inserting elements


In [96]:
np.insert(ar1,3,[1,2,3],axis=1)

array([[4, 7, 6, 1, 4, 4, 7],
       [3, 8, 7, 2, 3, 3, 8],
       [5, 2, 4, 3, 9, 9, 2]])

In [98]:
ar1 = np.insert(ar1,3,[1,2,3],axis=1)
ar1

array([[4, 7, 6, 1, 1, 4, 4, 7],
       [3, 8, 7, 2, 2, 3, 3, 8],
       [5, 2, 4, 3, 3, 9, 9, 2]])

# Deleting elements

In [99]:
ar1 = np.delete(ar1,(5,4),axis=1)

In [100]:
ar1

array([[4, 7, 6, 1, 4, 7],
       [3, 8, 7, 2, 3, 8],
       [5, 2, 4, 3, 9, 2]])

In [101]:
ar1 = np.insert(ar1,2,[9,9,9],axis=1)
ar1

array([[4, 7, 9, 6, 1, 4, 7],
       [3, 8, 9, 7, 2, 3, 8],
       [5, 2, 9, 4, 3, 9, 2]])

## inserting rows

In [102]:
ar1 = np.insert(ar1,1,[1,2,3,4,5,6,7],axis=0)

In [103]:
ar1

array([[4, 7, 9, 6, 1, 4, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [3, 8, 9, 7, 2, 3, 8],
       [5, 2, 9, 4, 3, 9, 2]])

# 

In [104]:
xa = np.array([4,5,78,234,645,6456,75,78,12,67])
np.sort(xa)

array([   4,    5,   12,   67,   75,   78,   78,  234,  645, 6456])

In [121]:
xb = np.array([1,4,7,9,6,23,78,17,5,45,12,33])
len(xb)
xc = xb.reshape(3,4)
xc

array([[ 1,  4,  7,  9],
       [ 6, 23, 78, 17],
       [ 5, 45, 12, 33]])

## sorting based on rows will ensure that the first row will have the least values and column values will stay intact


In [122]:
xr = np.sort(xc,axis=0)
xr

array([[ 1,  4,  7,  9],
       [ 5, 23, 12, 17],
       [ 6, 45, 78, 33]])

## sorting based on column will ensure that the first column will have least values and rows stay intact (this is also default sorting)

In [123]:
xd = np.sort(xc,axis=1)
xd

array([[ 1,  4,  7,  9],
       [ 6, 17, 23, 78],
       [ 5, 12, 33, 45]])

In [118]:
defaultsort = np.sort(xc)
defaultsort

array([[ 1,  4,  7,  9],
       [ 6, 12, 17, 23],
       [ 5, 33, 45, 78]])

# We are trying to look for a certain value inside a single dimensional array, this we could figure out based on a condition and figuring out the indices at where the condition matches or doesnt; 

In [124]:
y = np.array([3,6,5,7,8,1,9,10,4,2])

In [126]:
t1 = np.where(y<4)
t1

(array([0, 5, 9], dtype=int64),)

In [127]:
print(len(t1))

1


In [128]:
t1[0]

array([0, 5, 9], dtype=int64)

In [130]:
t1[0][0]

0

In [161]:
q = np.array([2,4,6,8,1])

## where are the values which meet a criteria 


In [162]:
z = np.where(q<4)
u=z[0]

## what are the values that meet the criteria

In [138]:
for i in range(len(z[0])):
    print(q[z[0][i]],end=',')

2,1,

In [164]:
q[z]

array([2, 1])

## how many values meet the critera

In [144]:
cnt = 0
for i in range(len(z[0])):
    cnt+=1
print("The nummber of values meeting the criteria are  ",end=str(cnt))

The nummber of values meeting the criteria are  2

In [146]:
(q<4).sum() #for how many values

2

## even and odd numbers filtering

In [176]:
c = np.array([11,43,56,87,98,234,56,89])

In [177]:
e = np.where(c%2==0)
a1 = e[0] #where the values are

In [178]:
even = c[a1] #what the even values are

In [179]:
o = np.where(c%2==1)
a2 = o[0]

In [180]:
odd = c[a2] #what the odd values are

In [182]:
even

array([ 56,  98, 234,  56])

In [183]:
odd

array([11, 43, 87, 89])

## where on 2D Array

In [190]:
ar2 = np.array([3,6,5,4,7,6,9,1,2,5,6,2])
ar2 = ar2.reshape(3,4)
ar2

array([[3, 6, 5, 4],
       [7, 6, 9, 1],
       [2, 5, 6, 2]])

In [194]:
p=np.where(ar2<4)
p

(array([0, 1, 2, 2], dtype=int64), array([0, 3, 0, 3], dtype=int64))

In [195]:
s=ar2[p]
s

array([3, 1, 2, 2])

In [193]:
len(p)

2

In [189]:
len(s)

4