In [244]:
import pandas as pd 
import numpy as np

In [245]:
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")

In [6]:
#Q axcp78 in mwh-2 or 3

In [140]:
new1=df[((df.Location=="MWH-2") | (df.Location=="MWH-3")) & (df.MaterialID=="AXCP-78")]

In [141]:
print(type(new1))

<class 'pandas.core.frame.DataFrame'>


In [24]:
new1

MaterialID Location  Quantity
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29

## numpy solution


In [246]:
t2= np.where(((df.Location=="MWH-2")|(df.Location=="MWH-3"))&(df.MaterialID=="AXCP-78"))
df.iloc[t2]


MaterialID Location  Quantity
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29

In [248]:
t2

(array([46, 47], dtype=int64),)

In [247]:
print(type(t2))

<class 'tuple'>


In [181]:
df1 = pd.read_excel("PandasExamples.xlsx",sheet_name="EmpInfo")
df1

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

# DATA CLEANING

In [63]:
df2=np.where(pd.isnull(df1))
df2

(array([2, 3, 5, 5, 6], dtype=int64), array([0, 2, 1, 2, 1], dtype=int64))

In [64]:
df1.iloc[df2]

Name    Deptt EmpID    Deptt EmpID
2     NaN    Admin  J436    Admin  J436
3   Arjun      NaN  A342      NaN  A342
5  Chetan      NaN   NaN      NaN   NaN
5  Chetan      NaN   NaN      NaN   NaN
6  Deepak  Quality   NaN  Quality   NaN

In [47]:
t1 = np.where(df1['Deptt'].isnull())
t1

(array([3, 5], dtype=int64),)

In [50]:
t1 = np.where((df1['Deptt'].isnull()) & (df1['EmpID'].isnull()))
df1.iloc[t1]

Name EmpID Deptt  Passport
5  Chetan   NaN   NaN  ER534867

In [57]:
df2=df1.drop(5)

In [58]:
df2

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

In [60]:
mdf = df1.dropna()
mdf

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

## dropping all null values

In [88]:
nonull =df1.dropna()
nonull

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

## splitting when empid is null

In [93]:
empnull = np.where(df1['EmpID'].isnull())
empnull

(array([5, 6], dtype=int64),)

In [100]:
#where empid has null values
df1.iloc[empnull[0]]

Name EmpID    Deptt  Passport
5  Chetan   NaN      NaN  ER534867
6  Deepak   NaN  Quality  RF453432

In [98]:
#dropping them now 
nulle = df1.drop(empnull[0],axis=0)
nulle

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278

split df into 2 parts where dept is null and other part

In [70]:
t2 = np.where(df1['Deptt'].isnull())
depnull=df1.iloc[t2]
depnull

Name EmpID Deptt  Passport
3   Arjun  A342   NaN  RF453432
5  Chetan   NaN   NaN  ER534867

In [86]:
t3=np.where(df1['Deptt'].isnull())[0]
t3
depnotnull = df1.drop(t3,axis=0)
depnotnull
#t3

Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278
6   Deepak   NaN  Quality  RF453432

## Removal of duplicate values

In [106]:
t4 = np.where(df1['Passport'].duplicated(keep=False))
t4

(array([0, 2, 3, 4, 6], dtype=int64),)

In [108]:
t5 = np.where(~df1['Passport'].duplicated(keep=False))
t5

(array([1, 5], dtype=int64),)

In [114]:
df1.iloc[t4[0]]

Name EmpID    Deptt  Passport
0  Sudeep  A342  Quality  DF453278
2     NaN  J436    Admin  DF453278
3   Arjun  A342      NaN  RF453432
4   Rishi  R475    Prodn  DF453278
6  Deepak   NaN  Quality  RF453432

In [115]:
df1.iloc[t5]

Name EmpID  Deptt  Passport
1  Ruchika  C578  Sales  CA567657
5   Chetan   NaN    NaN  ER534867

## data validation ensure that data follows certain contraints 


In [116]:
##values where quantity less than 50 and greater than 100

SyntaxError: invalid syntax (610349507.py, line 1)

In [117]:
erp = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")


In [136]:
t6= np.where((df.Quantity<=50)|(df.Quantity>=100))
derp1 = df.iloc[t6]

In [137]:
len(t6[0])

30

## group bys


In [209]:
testgrp = df.groupby(['Location'])
testgrp.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [151]:
grp1 = df.groupby('Location')
grp1

In [152]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [173]:
for p1,p2 in grp1:
    print(p1)
    print(p2)

MWH-1
   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39
MWH-2
   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
MWH-3
   MaterialID Location  Quantity
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
MWH-4
   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
4     AXCP-78    MW

In [183]:
grp1.get_group("MWH-2")

MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [188]:
grp1.agg(np.size)

MaterialID  Quantity
Location                      
MWH-1             11        11
MWH-2              9         9
MWH-3              4         4
MWH-4             15        15
MWH-5             11        11

In [196]:
grp1['Quantity'].agg(sum)

C:\Users\dheem\AppData\Local\Temp\ipykernel_15652\3474537928.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Quantity'].agg(sum)


Location
MWH-1    889
MWH-2    397
MWH-3    174
MWH-4    728
MWH-5    697
Name: Quantity, dtype: int64

In [202]:
mdf = grp1['Quantity'].agg([np.sum,np.mean])
mdf

C:\Users\dheem\AppData\Local\Temp\ipykernel_15652\779047664.py:1: FutureWarning: The provided callable <function sum at 0x0000011E32CC62A0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  mdf = grp1['Quantity'].agg([np.sum,np.mean])
C:\Users\dheem\AppData\Local\Temp\ipykernel_15652\779047664.py:1: FutureWarning: The provided callable <function mean at 0x0000011E32CC7380> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mdf = grp1['Quantity'].agg([np.sum,np.mean])


sum       mean
Location                
MWH-1     889  80.818182
MWH-2     397  44.111111
MWH-3     174  43.500000
MWH-4     728  48.533333
MWH-5     697  63.363636

In [203]:
mdf.iloc[np.where(mdf.index=="MWH-4")]

sum       mean
Location                
MWH-4     728  48.533333

In [204]:
grp2 = df.groupby(['Location','MaterialID'])
grp2.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [210]:
grp3 = df.groupby(['MaterialID','Location'])
grp3.groups

{('AXCP-78', 'MWH-1'): [1, 24, 25, 39, 48], ('AXCP-78', 'MWH-2'): [46], ('AXCP-78', 'MWH-3'): [47], ('AXCP-78', 'MWH-4'): [4], ('AXCP-78', 'MWH-5'): [3, 37, 38], ('DDBN-89', 'MWH-1'): [26, 40, 49], ('DDBN-89', 'MWH-2'): [45], ('DDBN-89', 'MWH-3'): [43], ('DDBN-89', 'MWH-4'): [22, 30], ('DDBN-89', 'MWH-5'): [23], ('GCVB-79', 'MWH-2'): [8, 15, 35, 36], ('GCVB-79', 'MWH-5'): [34], ('LXCV-21', 'MWH-2'): [2], ('LXCV-21', 'MWH-3'): [44], ('LXCV-21', 'MWH-5'): [27, 28, 29], ('SDRT-67', 'MWH-1'): [10, 41], ('SDRT-67', 'MWH-2'): [42], ('SDRT-67', 'MWH-4'): [11], ('SDRT-67', 'MWH-5'): [16, 17], ('TMI-43T', 'MWH-1'): [9], ('TMI-43T', 'MWH-2'): [7], ('TMI-43T', 'MWH-3'): [14], ('TMI-43T', 'MWH-4'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('TMI-43T', 'MWH-5'): [33]}

In [213]:
grp2.agg(np.sum)

C:\Users\dheem\AppData\Local\Temp\ipykernel_15652\481331680.py:1: FutureWarning: The provided callable <function sum at 0x0000011E32CC62A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp2.agg(np.sum)


Quantity
Location MaterialID          
MWH-1    AXCP-78          548
         DDBN-89          130
         SDRT-67           91
         TMI-43T          120
MWH-2    AXCP-78           85
         DDBN-89           69
         GCVB-79          156
         LXCV-21           27
         SDRT-67           31
         TMI-43T           29
MWH-3    AXCP-78           29
         DDBN-89           38
         LXCV-21           42
         TMI-43T           65
MWH-4    AXCP-78           36
         DDBN-89           75
         SDRT-67           58
         TMI-43T          559
MWH-5    AXCP-78          200
         DDBN-89           71
         GCVB-79           26
         LXCV-21          174
         SDRT-67          114
         TMI-43T          112

# Merging DF's

In [215]:
df1 = pd.read_excel("PandasExamples.xlsx",sheet_name="Pune")
df2 = pd.read_excel("PandasExamples.xlsx",sheet_name="Mumbai")

In [216]:
df1

Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [217]:
df2

Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [230]:
pd.merge(df1,df2,how='outer',on='Subject') ##outer means union

Name_x      Subject Grade_x    Name_y Grade_y
0   Hitesh   CommSkills       A     Arjun       A
1    Manoj     MLPython       C  Abhishek       B
2   Suyash  ProjectMgmt       B       NaN     NaN
3   Rakesh       Python       A    Chetan       A
4      NaN    Six Sigma     NaN   Vaibhav       A
5  Vaibhav   Statistics       B   Deepika       B

In [232]:
pd.merge(df1,df2,on=['Subject','Grade'],how='inner')

Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [249]:
pd.merge(df1,df2,on=['Subject','Grade'],how='outer') ##means union

Name_x      Subject Grade    Name_y
0   Hitesh   CommSkills     A     Arjun
1      NaN     MLPython     B  Abhishek
2    Manoj     MLPython     C       NaN
3   Suyash  ProjectMgmt     B       NaN
4   Rakesh       Python     A    Chetan
5      NaN    Six Sigma     A   Vaibhav
6  Vaibhav   Statistics     B   Deepika

In [236]:
pd.merge(df1,df2,on=['Subject'],how='outer')

Name_x      Subject Grade_x    Name_y Grade_y
0   Hitesh   CommSkills       A     Arjun       A
1    Manoj     MLPython       C  Abhishek       B
2   Suyash  ProjectMgmt       B       NaN     NaN
3   Rakesh       Python       A    Chetan       A
4      NaN    Six Sigma     NaN   Vaibhav       A
5  Vaibhav   Statistics       B   Deepika       B

In [239]:
dfa = pd.read_excel('PandasExamples.xlsx',sheet_name="Salary")
dfb = pd.read_excel('PandasExamples.xlsx',sheet_name="Deptt")

In [240]:
dfa

Name EmpID  Salary
0    Sudeep  A342      56
1   Deepika  J436      45
2    Chetan  B435      76
3  Abhishek  C234      47
4     Rishi  R475      38

In [241]:
dfb

Name EmpID        Deptt
0   Sudeep  A342      Quality
1  Ruchika  C578        Sales
2  Deepika  J436        Admin
3    Arjun  A342  Procurement
4    Rishi  R475        Prodn

In [243]:
pd.merge(dfa,dfb) ## if we dont define on clause it will merge all the common columns having common data

Name EmpID  Salary    Deptt
0   Sudeep  A342      56  Quality
1  Deepika  J436      45    Admin
2    Rishi  R475      38    Prodn

# Sorting

In [250]:
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")

In [251]:
df.head()

MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [253]:
x1 = np.array([4,0,7,2,1])

In [255]:
x2 = sorted(x1)
x2

[0, 1, 2, 4, 7]

In [257]:
x3 = np.argsort(x1)
x3

array([1, 4, 3, 0, 2], dtype=int64)

In [261]:
dfs = df.sort_values(['Quantity'])

In [263]:
dfs.tail()

MaterialID Location  Quantity
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
9     TMI-43T    MWH-1       120
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152

In [267]:
dfd = df.sort_values(['Location','Quantity','MaterialID'])
dfd

MaterialID Location  Quantity
40    DDBN-89    MWH-1        34
10    SDRT-67    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
41    SDRT-67    MWH-1        57
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
9     TMI-43T    MWH-1       120
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
8     GCVB-79    MWH-2        10
2     LXCV-21    MWH-2        27
36    GCVB-79    MWH-2        28
7     TMI-43T    MWH-2        29
35    GCVB-79    MWH-2        31
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
15    GCVB-79    MWH-2        87
47    AXCP-78    MWH-3        29
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
14    TMI-43T    MWH-3        65
30    DDBN-89    MWH-4        27
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
4     AXCP-78    MWH-4        36
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
22    DDBN-89    MWH-4        48
19    TMI-43T    MWH-4        52
11    SDRT-67    MWH-4        58
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
23    DDBN-89    MWH-5        71
27    LXCV-21    MWH-5        83
17    SDRT-67    MWH-5       102
33    TMI-43T    MWH-5       112